INSERT INTO product (PRODUCT_AVAILABLE, BRAND, CATEGORY, DESCRIPTION, NAME, PRICE, STOCK_QUANTITY, RELEASE_DATE)
VALUES (TRUE, 'Tesla', 'Electric Car', 'Electric luxury sedan', 'Tesla Model S', 79999.99, 15, '2024-01-15');

INSERT INTO product (PRODUCT_AVAILABLE, BRAND, CATEGORY, DESCRIPTION, NAME, PRICE, STOCK_QUANTITY, RELEASE_DATE)
VALUES (TRUE, 'BMW', 'SUV', 'Luxury SUV with advanced tech', 'BMW X5', 65999.50, 10, '2023-09-20');

INSERT INTO product (PRODUCT_AVAILABLE, BRAND, CATEGORY, DESCRIPTION, NAME, PRICE, STOCK_QUANTITY, RELEASE_DATE)
VALUES (TRUE, 'Audi', 'Sedan', 'Executive sedan with hybrid engine', 'Audi A6', 55999.00, 8, '2023-05-30');

INSERT INTO product (PRODUCT_AVAILABLE, BRAND, CATEGORY, DESCRIPTION, NAME, PRICE, STOCK_QUANTITY, RELEASE_DATE)
VALUES (TRUE, 'Ford', 'Sports Car', 'Iconic sports coupe', 'Ford Mustang', 45999.99, 5, '2022-12-01');
